version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/vue_sinergia/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: after-install.sh
      timeout: 300
      runas: root