version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/vue_sinergia/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
      - location: before-install.sh
        timeout: 1000
        runas: root
  AfterInstall:
    - location: after-install.sh
      timeout: 1000
      runas: root