version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html/vue_sinergia
    - source: /nod-modules
    destination: /var/www/html/vue_sinergia
    - source: /
    destination: /var/www/html/vue_sinergia
    - source: /
    destination: /var/www/html/vue_sinergia
    - source: /
    destination: /var/www/html/vue_sinergia
    recursive: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after-install.sh
      timeout: 300
      runas: root