version: 0.0
os: linux
files:
  - source: /vue_sinergia
    destination: /var/www/html/vue_sinergia
    recursive: true
hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after-install.sh
      timeout: 300
      runas: root